[workspace]
members = ["crates/cli","crates/zeevonk"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
zeevonk = { path = "crates/zeevonk" }

log = "0.4.29"
