[package]
name = "zv"
version.workspace = true
edition.workspace = true

[dependencies]
zeevonk = { workspace = true, features = ["server"] }

tokio.workspace = true

log.workspace = true
pretty_env_logger = "0.5.0"

anyhow = "1.0"
clap = { version = "4.5.53", features = ["derive"] }
